### ISSUE TITLE
Lock down log file

### ISSUE THREAD

**Issue by blockauditech** [MDLlife/MDL#12]
**cmd/mdl/mdl.go**
```
// init logging settings
func initLogging(dataDir string, level string, color, logtofile bool) (func(), error) {
[.......]
		// open log file
		tf := "2006-01-02-030405"
		logfile := filepath.Join(logDir,
			fmt.Sprintf("%s-v%s.log", time.Now().Format(tf), Version))
		var err error
		fd, err = os.OpenFile(logfile, os.O_RDWR|os.O_CREATE, 0666) // HERE
```

The permissions should be ideally 0600 (owner r/w) or 0640 (owner r/w, group read) max, otherwise the file is open to everyone to read and write to it which is not great from a security point of view.

**Comment by thomasmodeneis** [comment]
Thanks for the issue, we have fixed it.
Please get in contact on our support channel for your bounty reward.
