### ISSUE TITLE
Potential command injection

### ISSUE THREAD

**Issue by blockauditech** [MDLlife/MDL#13]
Probably not a lot of risk here since it looks like the data is currently coming from a config file, but still a good idea to sanitize _host_ before passing it on through the application.

**cmd/mdl/mdl.go**
```
// Run starts the mdl node
func Run(c *Config) {
[........]
	host := fmt.Sprintf("%s:%d", c.WebInterfaceAddr, c.WebInterfacePort)
	fullAddress := fmt.Sprintf("%s://%s", scheme, host)
[........]
if c.LaunchBrowser {
			wg.Add(1)
			go func() {
				defer wg.Done()

				// Wait a moment just to make sure the http interface is up
				time.Sleep(time.Millisecond * 100)

				logger.Info("Launching System Browser with %s", fullAddress)
				if err := browser.Open(fullAddress); err != nil { // HERE
					logger.Error(err.Error())
					return
				}
```
**browser.Open()** basically maps to https://github.com/toqueteos/webbrowser/blob/master/webbrowser.go where it doesn't ensure that params passed to it only contain host-looking characters, eg. alphanumeric only. It just executes them as a command where special characters could be injected and execute arbitrary commands.

```
func (b browserCommand) Command(s string) (*exec.Cmd, error) {
	u, err := url.Parse(s)
	if err != nil {
		return nil, err
	}

	validUrl := ensureValidURL(u)

	b.args = append(b.args, validUrl)

	return exec.Command(b.cmd, b.args...), nil
}
```

Easiest solution here is just sanitize _host_ and strip all non-alphanumeric (maybe allow -'s though) characters from it before passing it on to be used in the application.

References:
https://www.owasp.org/index.php/Data_Validation#Sanitize_with_Whitelist

**Comment by thomasmodeneis** [comment]
Thanks for the issue, we have fixed it.
Please get in contact on our support channel for your bounty reward.
