### ISSUE TITLE
0 value of transaction instead of its real value in UI

### ISSUE THREAD

**Issue by cyberbolt** [MDLlife/MDL#2]
In transaction explorer I see a transactions list. Some of them have 0 value. I know in our case we don't have real 0 value transactions. I think the number is just renders incorrectly. E.g. if you open transaction details you may notice there are actual values transferred (in Outputs section).

![image](https://user-images.githubusercontent.com/771535/36252911-24e18648-1257-11e8-89e9-d396af8d0287.png)

**Comment by morphium** [comment]
This one was fixed after merging with sky upstream
